name: Semgrep SAST
description: Semgrep SAST
author: 'Kong'
inputs:
  image:
    description: 'To pull image from DockerHub or AWS ECR'
    required: false
    type: choice
    options:
      - 'aws_ecr'
      - 'dockerHub'
  imageURL:
    description: 'AWS ECR Image URL'
    required: false

runs:
  using: composite
  steps:

    - name: SAST Scan
      # TODO: Define a tagging mechanism for dependency manager version updates 
      # Also for controlled rollouts
      uses: docker://${{imageURL}}/semgrep/semgrep@sha256:0cd75960cfec2215ff734a4f6379bbbb6edb82de0c24593dd0a70ec65e9860a9 # 1.114.0
      with:
        entrypoint: semgrep
        args:
          ci --config auto --sarif -o semgrep_${{ github.sha }}.sarif --no-autofix ${{ inputs.additional_config }}