name: Trivy Docker Scan
description: Scan a Docker image using Trivy from a private ECR repository
author: 'KONG'

inputs:
  scan_image:
    description: 'Docker image or tar file to scan'
    required: true
  output_file:
    description: 'Path to save the JSON report (required for JSON output)'
    required: false
  output_format:
    description: 'Specify the output format (e.g., json, table)'
    required: true
    default: json
  fail_build:
    description: 'Fail the build if vulnerability is found (only applicable for table format)'
    required: false
    default: 'false'
    type: choice
    options:
      - 'true'
      - 'false'
  ignore_unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: 'false'
    type: choice
    options:
      - 'true'
      - 'false'
  input_tar:
    description: 'Specify --input if using a tar file instead of an image reference'
    required: false
    default: ''
  trivy_db_cache:
    description: 'GitHub repository containing Trivy DB cache (format: owner/repo@ref)'
    required: false

runs:
  using: composite
  steps:
    - name: Generate docker-cis report
      # uses: docker://418272760313.dkr.ecr.us-east-1.amazonaws.com/k-internal/aquasec/trivy:0.59.0
      shell: bash
      run: |
        echo "naiya:" ${{ inputs.input_tar != '' && '--input ' || '' }}${{ inputs.input_tar != '' && inputs.input_tar || inputs.scan_image }} 
        docker run -v /home/runner/.cache/trivy:~/.cache/trivy 418272760313.dkr.ecr.us-east-1.amazonaws.com/k-internal/aquasec/trivy:0.59.0 image ${{ inputs.input_tar != '' && '--input ' || '' }}${{ inputs.input_tar != '' && inputs.input_tar || inputs.scan_image }} --compliance docker-cis-1.6.0 \
        ${{ inputs.trivy_db_cache != '' && '--cache-dir ~/.cache/trivy --skip-db-update' || '--db-repository 418272760313.dkr.ecr.us-east-1.amazonaws.com/ghcr/aquasecurity/trivy-db:2' }}
        echo "scan done"

      # with:
      #   entrypoint: trivy
      #   args: >
      #     image ${{ inputs.input_tar != '' && '--input ' || '' }}${{ inputs.input_tar != '' && inputs.input_tar || inputs.scan_image }}
      #     --compliance docker-cis-1.6.0
      #     -f ${{ inputs.output_format }}
      #     ${{ inputs.ignore_unfixed == 'true' && '--ignore-unfixed' || '' }}
      #     ${{ inputs.output_file != '' && format('-o {0}', inputs.output_file) || '' }}
      #     ${{ inputs.trivy_db_cache != '' && '--cache-dir ~/.cache/trivy --skip-db-update' || '--db-repository 418272760313.dkr.ecr.us-east-1.amazonaws.com/ghcr/aquasecurity/trivy-db:2' }}